test:
    resource: "@TestBundle/Controller/"
    type:     annotation
    prefix:   /test

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

app:
    resource: '@AppBundle/Controller/'
    type: annotation
